### PR TITLE
remove athens3 binary list

### PR DESCRIPTION
**Pull request by morde08**
# Description

- remove athens3 binary list as it is deprecated

# Is this deployed somewhere outside of the CI/CD process already, and if so, where?

- [ ] Developnet
- [ ] Athens-Validators
- [ ] Mainnet-Validators

# How Has This Been Tested?

# Checklist:

- [ ] I have performed a self-review of my code
- [ ] My changes generate no new warnings

[comment]: <## Env variables>

[comment]: <## Screenshots>

## Summary by CodeRabbit

- **Chores**
	- Removed the `binary_list.json` file, which previously listed download links for various binary releases of the `zetacored` application.

### CODE REVIEW

**Comment by julianrubino** [comment]
is Mainnet being used somewhere?

**Review by gartnera — COMMENTED** [review]
You'd still need this if you wanted to try and sync from zero right?

**Comment by morde08** [comment]
> is Mainnet being used somewhere?
@julianrubino I don't think so but I'm just staggering the deletes

**Comment by morde08** [comment]
> You'd still need this if you wanted to try and sync from zero right?

I don't think you NEED this list as if you were to fully sync from zero you could also just look at the list of releases on node repo. Not sure how much value having this separate file provides and it's overhead for us to keep it up to date.

**Comment by julianrubino** [comment]
> I don't think you NEED this list as if you were to fully sync from zero you could also just look at the list of releases on node repo. Not sure how much value having this separate file provides and it's overhead for us to keep it up to date.

You could watch proposals and then download the correct releases, but it's a bit painful to do that, it's easier if we could provide an upgrade path that can easily be automated to download all binaries and sync from genesis.

The bad thing is that we would need to maintain this

**Comment by gartnera** [comment]
I think we need to keep the old pre v19 list but I don't think we need to update this anymore so long as you set `DAEMON_ALLOW_DOWNLOAD_BINARIES=true`. You need to preload up to v19 based on the json then autodownload will should take care of the rest.

**Comment by CryptoFewka** [comment]
I 100% agree that we need to keep this at minimum for the pre v19 upgrade path. The same is also true for Mainnet. Closing the PR.

**Pull request closed without merging**
